services:
  dea_reader:
    build: .
    image: dea_reader:latest
    container_name: dea_reader
    privileged: true
    environment:
      - DATA_FOLDER=data
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - ./data:/app/data  # map host current dir to /app in container
    restart: unless-stopped
