services:
  dea_reader:
    build: .
    image: dea_reader:latest
    container_name: dea_reader
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - .:/app  # map host current dir to /app in container
    restart: unless-stopped
